// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: beef.proto

package pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindBeefRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindBeefRequest) Reset() {
	*x = FindBeefRequest{}
	mi := &file_beef_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindBeefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBeefRequest) ProtoMessage() {}

func (x *FindBeefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beef_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBeefRequest.ProtoReflect.Descriptor instead.
func (*FindBeefRequest) Descriptor() ([]byte, []int) {
	return file_beef_proto_rawDescGZIP(), []int{0}
}

type FindBeefResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beef map[string]uint32 `protobuf:"bytes,1,rep,name=beef,proto3" json:"beef,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *FindBeefResponse) Reset() {
	*x = FindBeefResponse{}
	mi := &file_beef_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindBeefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBeefResponse) ProtoMessage() {}

func (x *FindBeefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beef_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBeefResponse.ProtoReflect.Descriptor instead.
func (*FindBeefResponse) Descriptor() ([]byte, []int) {
	return file_beef_proto_rawDescGZIP(), []int{1}
}

func (x *FindBeefResponse) GetBeef() map[string]uint32 {
	if x != nil {
		return x.Beef
	}
	return nil
}

var File_beef_proto protoreflect.FileDescriptor

var file_beef_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x65, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x11, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x7f, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x65, 0x65, 0x66, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x62, 0x65, 0x65, 0x66, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42,
	0x65, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x65, 0x65, 0x66,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x62, 0x65, 0x65, 0x66, 0x1a, 0x37, 0x0a, 0x09, 0x42,
	0x65, 0x65, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x32, 0x44, 0x0a, 0x0b, 0x42, 0x65, 0x65, 0x66, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x65, 0x65, 0x66, 0x12,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x65,
	0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beef_proto_rawDescOnce sync.Once
	file_beef_proto_rawDescData = file_beef_proto_rawDesc
)

func file_beef_proto_rawDescGZIP() []byte {
	file_beef_proto_rawDescOnce.Do(func() {
		file_beef_proto_rawDescData = protoimpl.X.CompressGZIP(file_beef_proto_rawDescData)
	})
	return file_beef_proto_rawDescData
}

var file_beef_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_beef_proto_goTypes = []any{
	(*FindBeefRequest)(nil),  // 0: pb.FindBeefRequest
	(*FindBeefResponse)(nil), // 1: pb.FindBeefResponse
	nil,                      // 2: pb.FindBeefResponse.BeefEntry
}
var file_beef_proto_depIdxs = []int32{
	2, // 0: pb.FindBeefResponse.beef:type_name -> pb.FindBeefResponse.BeefEntry
	0, // 1: pb.BeefService.FindBeef:input_type -> pb.FindBeefRequest
	1, // 2: pb.BeefService.FindBeef:output_type -> pb.FindBeefResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_beef_proto_init() }
func file_beef_proto_init() {
	if File_beef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beef_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beef_proto_goTypes,
		DependencyIndexes: file_beef_proto_depIdxs,
		MessageInfos:      file_beef_proto_msgTypes,
	}.Build()
	File_beef_proto = out.File
	file_beef_proto_rawDesc = nil
	file_beef_proto_goTypes = nil
	file_beef_proto_depIdxs = nil
}
